#!/bin/bash
set -euo pipefail

# Incowgnito setup script
# Run from /opt/mailcow-dockerized:
#
#   cd /opt/mailcow-dockerized
#   curl -sL https://raw.githubusercontent.com/neorejalist/incowgnito/main/deploy/setup.sh | bash

REPO_BASE="https://raw.githubusercontent.com/neorejalist/incowgnito/main"

# ---------------------------------------------------------------------------
# Preflight
# ---------------------------------------------------------------------------

if [ ! -f mailcow.conf ]; then
  echo "Error: mailcow.conf not found. Run this script from /opt/mailcow-dockerized"
  exit 1
fi

source mailcow.conf

echo ""
echo "  ╦┌┐┌┌─┐┌─┐┬ ┬┌─┐┌┐┌┬┌┬┐┌─┐"
echo "  ║││││  │ │││││ ┬││││ │ │ │"
echo "  ╩┘└┘└─┘└─┘└┴┘└─┘┘└┘┴ ┴ └─┘"
echo ""
echo "  Setup for mailcow-dockerized"
echo "  Mailcow host: ${MAILCOW_HOSTNAME}"
echo ""

# ---------------------------------------------------------------------------
# Collect input
# ---------------------------------------------------------------------------

read -rp "App domain (e.g. incowgnito.eu): " APP_DOMAIN </dev/tty
read -rp "Alias domain (e.g. alias.incowgnito.eu or same as app): " ALIAS_DOMAIN </dev/tty

echo ""
echo "You'll need these from the Mailcow admin panel:"
echo "  - Admin > API > Read/Write key"
echo "  - Admin > OAuth2 Apps > Add Application"
echo "    Redirect URI: https://${APP_DOMAIN}/auth/callback"
echo ""

read -rp "Mailcow API key: " MAILCOW_API_KEY </dev/tty
read -rp "OAuth2 Client ID: " OAUTH_CLIENT_ID </dev/tty
read -rp "OAuth2 Client Secret: " OAUTH_CLIENT_SECRET </dev/tty

# ---------------------------------------------------------------------------
# Generate secrets
# ---------------------------------------------------------------------------

DB_USER="incowgnito"
DB_PASSWORD=$(openssl rand -hex 16)
SESSION_SECRET=$(openssl rand -hex 32)

echo ""
echo "Generated credentials:"
echo "  DB user:     ${DB_USER}"
echo "  DB password:  ${DB_PASSWORD:0:8}..."
echo "  Session key:  ${SESSION_SECRET:0:8}..."

# ---------------------------------------------------------------------------
# Write incowgnito.conf
# ---------------------------------------------------------------------------

cat > incowgnito.conf <<EOF
# Incowgnito configuration — generated by setup.sh
# MAILCOW_HOSTNAME, DBNAME, DBUSER, DBPASS inherited from mailcow.conf

MAILCOW_API_KEY=${MAILCOW_API_KEY}
MAILCOW_OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
MAILCOW_OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
RELAY_DOMAIN=${ALIAS_DOMAIN}
APP_URL=https://${APP_DOMAIN}
INCOWGNITO_DB_USER=${DB_USER}
INCOWGNITO_DB_PASSWORD=${DB_PASSWORD}
SESSION_SECRET=${SESSION_SECRET}
EOF

echo ""
echo "[1/6] Written incowgnito.conf"

# ---------------------------------------------------------------------------
# Write docker-compose.override.yml (merge-safe)
# ---------------------------------------------------------------------------

INCOWGNITO_SERVICE_BLOCK='
    incowgnito:
      image: ghcr.io/neorejalist/incowgnito:latest
      container_name: incowgnito
      restart: unless-stopped
      env_file:
        - mailcow.conf
        - incowgnito.conf
      networks:
        mailcow-network:
      depends_on:
        - mysql-mailcow
        - nginx-mailcow
      healthcheck:
        test: ["CMD", "wget", "-qO-", "http://localhost:3000/session-info"]
        interval: 30s
        timeout: 5s
        retries: 3
        start_period: 10s'

COMPOSE_OK=true

if [ -f docker-compose.override.yml ]; then
  if grep -q "incowgnito" docker-compose.override.yml; then
    echo "[2/6] docker-compose.override.yml already contains incowgnito, skipping"
  else
    cp docker-compose.override.yml docker-compose.override.yml.bak
    echo "${INCOWGNITO_SERVICE_BLOCK}" >> docker-compose.override.yml

    if docker compose config --quiet 2>/dev/null; then
      echo "[2/6] Appended incowgnito service to docker-compose.override.yml (backup: docker-compose.override.yml.bak)"
    else
      cp docker-compose.override.yml.bak docker-compose.override.yml
      COMPOSE_OK=false
      echo "[2/6] Warning: failed to merge into existing docker-compose.override.yml"
      echo "      Restored from backup. Add the incowgnito service manually:"
      echo "      https://github.com/neorejalist/incowgnito#setup"
    fi
  fi
else
  printf "services:\n%s\n" "${INCOWGNITO_SERVICE_BLOCK}" > docker-compose.override.yml

  if docker compose config --quiet 2>/dev/null; then
    echo "[2/6] Created docker-compose.override.yml"
  else
    rm -f docker-compose.override.yml
    COMPOSE_OK=false
    echo "[2/6] Warning: generated docker-compose.override.yml failed validation"
    echo "      Create it manually using the reference at:"
    echo "      https://github.com/neorejalist/incowgnito#setup"
  fi
fi

# ---------------------------------------------------------------------------
# Write nginx config
# ---------------------------------------------------------------------------

mkdir -p data/conf/nginx

cat > "data/conf/nginx/incowgnito.conf" <<NGINX
server {
    listen 80;
    server_name ${APP_DOMAIN};
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ${APP_DOMAIN};

    ssl_certificate     /etc/ssl/mail/cert.pem;
    ssl_certificate_key /etc/ssl/mail/key.pem;

    ssl_protocols             TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_session_cache         shared:SSL:10m;
    ssl_session_timeout       10m;

    add_header Strict-Transport-Security "max-age=63072000" always;
    add_header X-Frame-Options DENY always;
    add_header X-Content-Type-Options nosniff always;

    location / {
        proxy_pass         http://incowgnito:3000;
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto https;
        proxy_set_header   X-Forwarded-Host  \$host;
        proxy_read_timeout 90s;
    }
}
NGINX

echo "[3/6] Written data/conf/nginx/incowgnito.conf"

# ---------------------------------------------------------------------------
# Add domain to ADDITIONAL_SAN
# ---------------------------------------------------------------------------

DOMAINS_TO_ADD="${APP_DOMAIN}"
if [ "${APP_DOMAIN}" != "${ALIAS_DOMAIN}" ]; then
  DOMAINS_TO_ADD="${APP_DOMAIN},${ALIAS_DOMAIN}"
fi

CURRENT_SAN=$(grep "^ADDITIONAL_SAN=" mailcow.conf 2>/dev/null | cut -d'=' -f2- || echo "")

NEEDS_UPDATE=false
for DOMAIN in $(echo "${DOMAINS_TO_ADD}" | tr ',' ' '); do
  if ! echo ",${CURRENT_SAN}," | grep -q ",${DOMAIN},"; then
    NEEDS_UPDATE=true
    if [ -z "${CURRENT_SAN}" ]; then
      CURRENT_SAN="${DOMAIN}"
    else
      CURRENT_SAN="${CURRENT_SAN},${DOMAIN}"
    fi
  fi
done

if [ "${NEEDS_UPDATE}" = true ]; then
  if grep -q "^ADDITIONAL_SAN=" mailcow.conf; then
    sed -i "s|^ADDITIONAL_SAN=.*|ADDITIONAL_SAN=${CURRENT_SAN}|" mailcow.conf
  else
    echo "ADDITIONAL_SAN=${CURRENT_SAN}" >> mailcow.conf
  fi
  echo "[4/6] Updated ADDITIONAL_SAN in mailcow.conf: ${CURRENT_SAN}"
  echo "      Running certdumper to obtain certificate..."
  docker compose run --rm certdumper 2>/dev/null || echo "      Warning: certdumper failed — you may need to run it manually"
else
  echo "[4/6] Domains already in ADDITIONAL_SAN, skipping"
fi

# ---------------------------------------------------------------------------
# Set up database
# ---------------------------------------------------------------------------

echo "[5/6] Setting up database..."

docker compose exec -T mysql-mailcow mysql -u"${DBUSER}" -p"${DBPASS}" "${DBNAME}" <<SQL

CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASSWORD}';

CREATE TABLE IF NOT EXISTS incowgnito_users (
  id          VARCHAR(36) PRIMARY KEY,
  email       VARCHAR(255) UNIQUE NOT NULL,
  username    VARCHAR(255) NOT NULL,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS incowgnito_api_keys (
  id           VARCHAR(36) PRIMARY KEY,
  user_id      VARCHAR(36) NOT NULL,
  key_hash     VARCHAR(128) UNIQUE NOT NULL,
  name         VARCHAR(255) NOT NULL DEFAULT 'Default',
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_used_at DATETIME,
  FOREIGN KEY (user_id) REFERENCES incowgnito_users(id) ON DELETE CASCADE
);

GRANT SELECT (id, address, goto, active, created, modified, domain) ON ${DBNAME}.alias TO '${DB_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ${DBNAME}.incowgnito_users TO '${DB_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ${DBNAME}.incowgnito_api_keys TO '${DB_USER}'@'%';

FLUSH PRIVILEGES;

SQL

echo "      Database user and tables created"

# ---------------------------------------------------------------------------
# Start
# ---------------------------------------------------------------------------

if [ "${COMPOSE_OK}" = true ]; then
  echo "[6/6] Pulling and starting Incowgnito..."
  docker compose pull incowgnito 2>/dev/null
  docker compose up -d incowgnito 2>/dev/null
  docker compose exec nginx-mailcow nginx -s reload 2>/dev/null

  echo ""
  echo "  Setup complete!"
  echo ""
  echo "  App:     https://${APP_DOMAIN}"
  echo "  Aliases: *@${ALIAS_DOMAIN}"
  echo ""
  echo "  Next steps:"
  echo "  1. Visit https://${APP_DOMAIN} and log in with your mailcow account"
  echo "  2. Create an API key from the dashboard"
  echo "  3. Configure Bitwarden: Settings > Email Alias > addy.io"
  echo "     API URL:         https://${APP_DOMAIN}"
  echo "     Default Domain:  ${ALIAS_DOMAIN}"
else
  echo "[6/6] Skipped — fix docker-compose.override.yml first, then run:"
  echo "  docker compose pull incowgnito && docker compose up -d incowgnito"
  echo "  docker compose exec nginx-mailcow nginx -s reload"
fi

echo ""
